version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "priority: low"
      - "status: review needed"
      - "type: maintenance"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "priority: low"
      - "status: review Needed"
      - "type: maintenance"
