name: Synchronize labels

on:
  push:
    branches:
      - main
    paths:
      - ./labels.yml
  pull_request:
    branches:
      - main
    paths:
      - ./labels.yml
  workflow_dispatch:

permissions:
  issues: write

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: true
          config-file: ./labels.yml
